
  TYPES:
     - general_contractor
     - permit_owner

  1:
      1:
          - None
          - None
          - general_contractor_license_expiration_date
          - general_contractor_license_number
          - permit_owner_mail
          - None