services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /home/ubuntu/certs:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
    networks:
      - doc-construct-app-network
    restart: unless-stopped

  frontend:
    build:
      context: ./DocConstructFe
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      - NEXT_PUBLIC_URL=${NEXT_PUBLIC_URL}
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - doc-construct-app-network

  backend:
    build:
      context: ./DocConstructBe
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - app_data:/app/data
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - APP_PATH=/app/data
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@postgres:5432/${DB_NAME} 
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - doc-construct-app-network

  postgres:
    image: postgres:15-alpine
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./postgres.conf:/etc/postgresql/postgresql.conf:ro
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    env_file:
      - .env
    networks:
      - doc-construct-app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  doc-construct-app-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  app_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${APP_PATH}
