TYPES:
    - supervisor_engineer_architecture

1:
  1:
    - supervisor_engineer_architecture_id
    - None
    - None
    - supervisor_engineer_architecture_license_number 
    - supervisor_engineer_architecture_name
    - None
    - None
    - supervisor_engineer_architecture_phone
    - None
    - supervisor_engineer_architecture_name
    



