DOCUMENT_FIELD_COORDINATE_MAP:
  TRASH_INSPECTION:
    1:  
      supervisor_engineer_name: [380, 424]
      supervisor_engineer_id: [240, 424] 
      supervisor_engineer_license_number: [100, 424]
      supervisor_engineer_phone: [435, 405]
      supervisor_engineer_address: [390, 385]
      supervisor_engineer_mail: [250, 405]
      supervisor_engineer_name_for_signed: [130, 190]
      date_for_signed: [140, 172]

  ADAPTER_AGREEMENT:
    1:
      structural_engineer_name: [300, 400]
      structural_engineer_id: [80, 400]
      structural_engineer_phone: [450, 365]
      structural_engineer_license_number: [480, 382]
      structural_engineer_address: [330, 350]
      structural_engineer_mail: [250, 365]
      structural_engineer_date: [80, 265]
      permit_owner: [350, 415]
      permit_owner_name_for_signed: [80, 290]
      date_for_signed: [80, 265]
    2:
      structural_engineer_name: [320, 727]  
      structural_engineer_id: [150, 727]    
      structural_engineer_phone: [425, 708] 
      structural_engineer_address: [333, 694] 
      structural_engineer_mail: [200, 707] 
      structural_engineer_name_for_signed: [80, 440]
      date_for_signed: [80, 405] 
      
  START_WORK_REQUEST:
    1:
      construction_inspection_officer_name: [370, 427]
      construction_inspection_officer_id: [100, 427]
      construction_inspection_officer_license_number: [400,410]
      construction_inspection_officer_phone: [190, 410]
      construction_inspection_officer_address: [230, 393]
      construction_inspection_officer_mail: [390, 393]
      construction_inspection_officer_name_for_signed: [120, 145]
      date_for_signed: [100, 120]

  STRUCTURAL_SUPERVISOR:
    1:
      general_contractor_name: [430, 365]
      general_contractor_id: [430, 345]
      general_contractor_license_number:  [150, 345]
      general_contractor_license_expiration_date: [460, 330]
      general_contractor_phone: [430, 315]
      general_contractor_mail: [300, 315]
      general_contractor_address: [430, 295]

      structural_engineer_name: [130, 280]
      structural_engineer_id: [450, 270]
      structural_engineer_license_number: [300, 270]
      structural_engineer_phone: [420, 250]
      structural_engineer_mail: [300, 250]
      structural_engineer_address: [450, 235]
      general_contractor_name_for_signed: [120, 185]
      date_for_signed: [100, 160]
    2:
      structural_engineer_name: [395, 727]
      structural_engineer_id:  [430, 712]
      structural_engineer_license_number: [300, 712]
      structural_engineer_phone: [160, 712]
      structural_engineer_mail: [30, 712]
      structural_engineer_address: [350, 680]
      structural_engineer_name_for_signed: [120, 455]
      date_for_signed: [100, 425]

  EXECUTION_INSPECTION:
    1:
      permit_owner: [395, 390]
      general_contractor_name: [355, 370]
      general_contractor_id: [150, 370]
      general_contractor_license_number: [430, 355]
      general_contractor_phone: [430, 338]
      general_contractor_mail: [320, 338]
      general_contractor_address: [430, 320]
      permit_owner_name_for_signed: [90, 255]
      date_for_signed: [90, 230]
    2:
      general_contractor_name: [350, 730]
      general_contractor_id: [420, 710]
      general_contractor_license_number: [300, 710]
      general_contractor_phone: [420, 690]
      general_contractor_mail: [300, 690]
      general_contractor_address: [360, 675]
    3:
      general_contractor_name_for_signed: [100, 625]
      date_for_signed: [90, 597]

  PESTICIDAL_OWNER:
    1:
      pesticidal_name: [380, 632]
      pesticidal_id: [100, 632]
      pesticidal_phone: [235, 607]
      pesticidal_address: [420, 607]
      pesticidal_mail: [270, 580]
      permit_owner: [260, 456]
      date: [435, 456]
      pesticidal_name_for_signed: [415, 392]
      pesticidal_id_for_signed: [277, 392]
      pesticidal_license_number: [120, 392]
      date_for_signed: [200, 256]
 
  CONTRACTOR_OWNER:
    1:
      permit_owner: [395, 390]
      general_contractor_name: [355, 370]
      general_contractor_id: [430, 355]
      general_contractor_license_number: [310, 355]
      general_contractor_phone: [430, 338]
      general_contractor_mail: [310, 338]
      general_contractor_address: [430, 320]
      permit_owner_name_for_signed: [90, 270]
      date_for_signed: [90, 245]
    2:
      general_contractor_name: [430, 712]
      general_contractor_id: [120, 712]
      general_contractor_license_number: [410, 695]
      general_contractor_license_expiration_date: [200, 695]
      general_contractor_phone: [420, 680]
      general_contractor_mail: [280, 680]
      general_contractor_address: [400, 665]
      general_contractor_name_for_signed: [120, 480]
      date_for_signed: [100, 455]

DOCUMENT_PROFESSIONAL_MAP:
  TRASH_INSPECTION:
    - SUPERVISOR_ENGINEER

  ADAPTER_AGREEMENT:
    - STRUCTURAL_ENGINEER

  START_WORK_REQUEST:
    - CONSTRUCTION_INSPECTION_OFFICER

  STRUCTURAL_SUPERVISOR:
    - STRUCTURAL_ENGINEER
    - GENERAL_CONTRACTOR

  EXECUTION_INSPECTION:
    - GENERAL_CONTRACTOR

  PESTICIDAL_OWNER:
    - PESTICIDAL

  CONTRACTOR_OWNER:
    - GENERAL_CONTRACTOR
