DOCUMENT_FIELD_COORDINATE_MAP:
  TRASH_INSPECTION:
    1:  
      name: [380, 424]
      id: [240, 424] 
      license_number: [100, 424]
      phone: [435, 405]
      address: [390, 385]
      mail: [250, 405]
      prof_name_for_signed: [130, 190]
      date_for_signed: [140, 172]

  ADAPTER_AGREEMENT:
    1:
      name: [300, 400]
      id: [80, 400]
      phone: [450, 365]
      license_number: [480, 382]
      address: [330, 350]
      mail: [250, 365]
      date: [80, 265]
      permit_owner: [350, 415]
      permit_owner_name_for_signed: [80, 290]
    2:
      name: [320, 727]  
      id: [150, 727]    
      phone: [425, 708] 
      address: [333, 694] 
      mail: [200, 707] 
      name_for_signed: [80, 440]
      date_for_signed: [80, 405] 
      
  START_WORK_REQUEST:
    1:
      name: [370, 427]
      id: [100, 427]
      license_number: [400,410]
      phone: [190, 410]
      address: [230, 393]
      mail: [390, 393]
      prof_name_for_signed: [120, 145]
      date_for_signed: [100, 120]

  STRUCTURAL_SUPERVISOR:
    1:
      name: [000, 424]
      id: [000, 424]
      phone: [000, 405]
      address: [000, 385]
      mail: [00, 405]

  EXECUTION_INSPECTION:
    1:
      permit_owner: [395, 390]
      name: [355, 370]
      id: [150, 370]
      license_number: [430, 355]
      phone: [430, 338]
      mail: [320, 338]
      address: [430, 320]
      permit_owner_name_for_signed: [90, 255]
      date_for_signed: [90, 230]
    2:
      name: [350, 730]
      id: [420, 710]
      license_number: [300, 710]
      phone: [420, 690]
      mail: [300, 690]
      address: [360, 675]
    3:
      name_for_signed: [100, 625]
      date_for_signed: [90, 597]

  PESTICIDAL_OWNER:
    1:
      name: [380, 632]
      id: [100, 632]
      phone: [235, 607]
      address: [420, 607]
      mail: [270, 580]
      permit_owner: [260, 456]
      date_for_signed: [435, 456]
      prof_name_for_signed: [415, 392]
      id_for_signed: [277, 392]
      license_number: [120, 392]
      
      date_for_prof_signed: [200, 256]
 
  CONTRACTOR_OWNER:
    1:
      permit_owner: [395, 390]
      name: [355, 370]
      id: [430, 355]
      license_number: [310, 355]
      phone: [430, 338]
      mail: [310, 338]
      address: [430, 320]
      permit_owner_name_for_signed: [90, 270]
      date_for_signed: [90, 245]
    2:
      name: [430, 712]
      id: [120, 712]
      license_number: [410, 695]
      license_expiration_date: [200, 695]
      phone: [420, 680]
      mail: [280, 680]
      address: [400, 665]
      prof_name_for_signed: [120, 480]
      date_for_signed: [100, 455]

DOCUMENT_PROFESSIONAL_MAP:
  TRASH_INSPECTION:
    - SUPERVISOR_ENGINEER

  ADAPTER_AGREEMENT:
    - STRUCTURAL_ENGINEER

  START_WORK_REQUEST:
    - CONSTRUCTION_INSPECTION_OFFICER

  STRUCTURAL_SUPERVISOR:
    - STRUCTURAL_ENGINEER

  EXECUTION_INSPECTION:
    - GENERAL_CONTRACTOR

  PESTICIDAL_OWNER:
    - PESTICIDAL

  CONTRACTOR_OWNER:
    - GENERAL_CONTRACTOR
