DOCUMENT_FIELD_COORDINATE_MAP:
  TRASH_INSPECTION:
    1:
      supervisor_engineer_name: [372, 428]
      supervisor_engineer_id: [235, 428]
      supervisor_engineer_license_number: [98, 428]
      supervisor_engineer_phone: [426, 409]
      supervisor_engineer_address: [382, 388]
      supervisor_engineer_mail: [245, 409]
      supervisor_engineer_name_for_signed: [127, 191]
      date_for_signed: [137, 173]
  
  ADAPTER_AGREEMENT:
    1:
      structural_engineer_name: [294, 402]
      structural_engineer_id: [78, 402]
      structural_engineer_phone: [441, 368]
      structural_engineer_license_number: [470, 385]
      structural_engineer_address: [323, 351]
      structural_engineer_mail: [245, 368]
      structural_engineer_date: [78, 267]
      permit_owner_name: [343, 419]
      permit_owner_name_for_signed: [78, 292]
      date_for_signed: [78, 267]
    2:
      structural_engineer_name: [313, 731]
      structural_engineer_id: [147, 731]
      structural_engineer_phone: [416, 713]
      structural_engineer_address: [326, 695]
      structural_engineer_mail: [196, 713]
      structural_engineer_name_for_signed: [78, 444]
      date_for_signed: [78, 409]
  
  START_WORK_REQUEST:
    1:
      construction_inspection_officer_name: [362, 431]
      construction_inspection_officer_id: [98, 431]
      construction_inspection_officer_license_number: [392, 414]
      construction_inspection_officer_phone: [186, 414]
      construction_inspection_officer_address: [225, 396]
      construction_inspection_officer_mail: [382, 396]
      construction_inspection_officer_name_for_signed: [117, 146]
      date_for_signed: [98, 121]
  
  STRUCTURAL_SUPERVISOR:
    1:
      general_contractor_name: [407, 368]
      general_contractor_id: [421, 348]
      general_contractor_license_number: [147, 348]
      general_contractor_license_expiration_date: [450, 333]
      general_contractor_phone: [421, 315]
      general_contractor_mail: [294, 315]
      general_contractor_address: [360, 297]
      structural_engineer_name: [127, 282]
      structural_engineer_id: [441, 269]
      structural_engineer_license_number: [294, 269]
      structural_engineer_phone: [414, 252]
      structural_engineer_mail: [294, 252]
      structural_engineer_address: [382, 235]
      general_contractor_name_for_signed: [80, 186]
      date_for_signed: [98, 161]
    2:
      structural_engineer_name: [387, 730]
      structural_engineer_id: [421, 713]
      structural_engineer_license_number: [294, 713]
      structural_engineer_phone: [156, 713]
      structural_engineer_mail: [29, 713]
      structural_engineer_address: [343, 680]
      structural_engineer_name_for_signed: [117, 459]
      date_for_signed: [88, 426]
  
  EXECUTION_INSPECTION:
    1:
      permit_owner_name: [387, 390]
      general_contractor_name: [330, 373]
      general_contractor_id: [147, 373]
      general_contractor_license_number: [421, 358]
      general_contractor_phone: [421, 341]
      general_contractor_mail: [313, 341]
      general_contractor_address: [367, 323]
      permit_owner_name_for_signed: [88, 257]
      date_for_signed: [88, 232]
    2:
      general_contractor_name: [343, 730]
      general_contractor_id: [416, 712]
      general_contractor_license_number: [294, 712]
      general_contractor_phone: [416, 696]
      general_contractor_mail: [294, 696]
      general_contractor_address: [352, 677]
    3:
      general_contractor_name_for_signed: [80, 631]
      date_for_signed: [88, 603]
  
  PESTICIDAL_OWNER:
    1:
      pesticidal_name: [372, 638]
      pesticidal_id: [98, 638]
      pesticidal_phone: [230, 603]
      pesticidal_address: [411, 603]
      pesticidal_mail: [264, 573]
      permit_owner_name: [254, 460]
      date: [445, 460]
      pesticidal_name_for_signed: [406, 395]
      pesticidal_id_for_signed: [271, 395]
      pesticidal_license_number: [117, 395]
      date_for_signed: [196, 258]
  
  CONTRACTOR_OWNER:
    1:
      permit_owner_name: [387, 393]
      general_contractor_name: [320, 373]
      general_contractor_id: [421, 350]
      general_contractor_license_number: [303, 350]
      general_contractor_phone: [425, 333]
      general_contractor_mail: [284, 333]
      general_contractor_address: [355, 315]
      permit_owner_name_for_signed: [88, 272]
      date_for_signed: [88, 247]
    2:
      general_contractor_name: [360, 715]
      general_contractor_id: [117, 715]
      general_contractor_license_number: [401, 695]
      general_contractor_license_expiration_date: [196, 695]
      general_contractor_phone: [413, 675]
      general_contractor_mail: [274, 675]
      general_contractor_address: [360, 660]
      general_contractor_name_for_signed: [60, 484]
      date_for_signed: [98, 459]
  
  PROJECT_TEAMS:
    1:
      permit_owner_name: [588, 398]
      permit_owner_phone: [509, 398]
      permit_owner_mail: [372, 398]
      permit_owner_address: [147, 398]
      permit_owner_representative_name: [588, 353]
      permit_owner_representative_phone: [509, 353]
      permit_owner_representative_mail: [372, 353]
      permit_owner_representative_address: [147, 353]
      request_editor_name: [588, 313]
      request_editor_phone: [509, 313]
      request_editor_mail: [372, 313]
      request_editor_address: [147, 313]
      structural_engineer_name: [588, 272]
      structural_engineer_phone: [509, 272]
      structural_engineer_mail: [372, 272]
      structural_engineer_address: [147, 272]
      general_contractor_name: [588, 232]
      general_contractor_phone: [509, 232]
      general_contractor_mail: [372, 232]
      general_contractor_address: [147, 232]
      contractor_representative_name: [588, 181]
      contractor_representative_phone: [509, 181]
      contractor_representative_mail: [372, 181]
      contractor_representative_address: [147, 181]
      project_manager_name: [588, 131]
      project_manager_phone: [509, 131]
      project_manager_mail: [372, 131]
      project_manager_address: [147, 131]





DOCUMENT_PROFESSIONAL_MAP:
  TRASH_INSPECTION:
    - SUPERVISOR_ENGINEER

  ADAPTER_AGREEMENT:
    - STRUCTURAL_ENGINEER

  START_WORK_REQUEST:
    - CONSTRUCTION_INSPECTION_OFFICER

  STRUCTURAL_SUPERVISOR:
    - STRUCTURAL_ENGINEER
    - GENERAL_CONTRACTOR

  EXECUTION_INSPECTION:
    - GENERAL_CONTRACTOR

  PESTICIDAL_OWNER:
    - PESTICIDAL

  CONTRACTOR_OWNER:
    - GENERAL_CONTRACTOR

  PROJECT_TEAMS:
    - PERMIT_OWNER
    - REQUEST_EDITOR
    - CONTRACTOR_REPRESENTATIVE
    - PROJECT_MANAGER
    - PERMIT_OWNER_REPRESENTATIVE
    - STRUCTURAL_ENGINEER
    - GENERAL_CONTRACTOR