DOCUMENT_FIELD_COORDINATE_MAP:
  TRASH_INSPECTION:
    1:  
      name: [380, 424]
      id: [240, 424] 
      license_number: [100, 424]
      phone: [435, 405]
      address: [390, 385]
      mail: [250, 405]
      prof_name_for_signed: [130, 190]
      date_for_signed: [140, 172]

  ADAPTER_AGREEMENT:
    1:
      name: [300, 400]
      id: [80, 400]
      phone: [450, 365]
      license_number: [480, 382]
      address: [330, 350]
      mail: [250, 365]
      date: [80, 265]
      permit_owner: [350, 407]
      permit_owner_name_for_signed: [80, 290]
    2:
      name: [320, 727]  
      id: [150, 727]    
      phone: [425, 708] 
      address: [333, 694] 
      mail: [200, 707] 
      name_for_signed: [80, 440]
      date_for_signed: [80, 405] 
      

  START_WORK_REQUEST:
    1:
      name: [370, 427]
      id: [100, 427]
      license_number: [400,410]
      phone: [190, 410]
      address: [230, 393]
      mail: [390, 393]
      prof_name_for_signed: [120, 145]
      date_for_signed: [100, 120]

  EXECUTION_LICENSE:
    1:
      name: [380, 424]
      id: [100, 424]
      phone: [435, 405]
      address: [380, 385]
      mail: [220, 405]

  EXECUTION_INSPECTION:
    1:
      name: [150, 250]
      id: [350, 250]
      phone: [550, 250]
      address: [250, 350]

  PESTICIDAL_OWNER:
    1:
      name: [380, 632]
      id: [100, 632]
      phone: [235, 607]
      address: [420, 607]
      mail: [270, 580]
      permit_owner: [260, 456]
      date_for_signed: [435, 456]
      prof_name_for_signed: [415, 392]
      id_for_signed: [277, 392]
      license_number: [120, 392]
      
      date_for_prof_signed: [200, 256]


DOCUMENT_PROFESSIONAL_MAP:
  TRASH_INSPECTION:
    - SUPERVISOR_ENGINEER

  ADAPTER_AGREEMENT:
    - STRUCTURAL_ENGINEER

  START_WORK_REQUEST:
    - CONSTRUCTION_INSPECTION_OFFICER

  EXECUTION_LICENSE:
    - STRUCTURAL_ENGINEER

  EXECUTION_INSPECTION:
    - GENERAL_CONTRACTOR

  PESTICIDAL_OWNER:
    - PESTICIDAL
