DOCUMENT_FIELD_COORDINATE_MAP:
  TRASH_INSPECTION:
    1:  
      name: [380, 424]
      id: [240, 424] 
      license_number: [100, 424]
      phone: [435, 405]
      address: [390, 385]
      mail: [250, 405]
      prof_name_for_signed: [130, 190]
      date_for_signed: [140, 172]

  ADAPTER_AGREEMENT:
    1:
      name: [300, 400]
      id: [80, 400]
      phone: [450, 365]
      license_number: [480, 382]
      address: [330, 350]
      mail: [250, 365]
      date: [80, 265]
      permit_owner: [340, 420]
      permit_owner_name_for_signed: [80, 290]
    2:
      name: [300, 400]  
      id: [80, 400]    
      phone: [450, 365] 
      address: [330, 350] 
      mail: [250, 365] 
      signed_name: [200, 300]
      date_for_signed: [80, 290] 

  START_WORK_REQUEST:
    1:
      name: [372, 426]
      id: [100, 426]
      license_number: [365,410]
      phone: [195, 410]
      address: [220, 393]
      mail: [385, 393]
      prof_name_for_signed: [120, 145]
      date_for_signed: [120, 120]

  EXECUTION_LICENSE:
    1:
      name: [380, 424]
      id: [100, 424]
      phone: [435, 405]
      address: [380, 385]
      mail: [220, 405]

  EXECUTION_INSPECTION:
    1:
      name: [150, 250]
      id: [350, 250]
      phone: [550, 250]
      address: [250, 350]

  PESTICIDAL_OWNER:
    1:
      name: [380, 630]
      id: [100, 630]
      phone: [235, 607]
      address: [420, 607]
      mail: [260, 582]
      permit_owners: [260, 425]
      date_for_signed: [425, 455]
      prof_name_for_signed: [400, 393]
      id_for_signed: [280, 393]
      license_number: [120, 393]
      
      date_for_prof_signed: [210, 260]


DOCUMENT_PROFESSIONAL_MAP:
  TRASH_INSPECTION:
    - SUPERVISOR_ENGINEER

  ADAPTER_AGREEMENT:
    - STRUCTURAL_ENGINEER

  START_WORK_REQUEST:
    - CONSTRUCTION_INSPECTION_OFFICER

  EXECUTION_LICENSE:
    - STRUCTURAL_ENGINEER

  EXECUTION_INSPECTION:
    - GENERAL_CONTRACTOR

  PESTICIDAL_OWNER:
    - PESTICIDAL
