
TYPES:
    - general_contractor
    - permit_owner

2:
    1:
        - None
        - date
        - permit_owner_name
        - general_contractor_address
        - general_contractor_mail 
        - general_contractor_phone
        - general_contractor_license_number
        - general_contractor_id
        - general_contractor_name
        - permit_owner_name
    2:
        - None
        - None
        - None
        - None
        - None
        - None
        - None
        - date
        - general_contractor_name
        - general_contractor_address
        - general_contractor_mail
        - general_contractor_phone
        - general_contractor_license_expiration_date
        - general_contractor_license_number
        - general_contractor_id
        - general_contractor_name

3:
    1:
        - None
        - date
        - permit_owner_name
        - general_contractor_address
        - general_contractor_mail 
        - general_contractor_phone
        - general_contractor_license_number
        - general_contractor_id
        - general_contractor_name
        - permit_owner_name
    2:
        - None
        - None
        - None
        - None
        - None
        - None
        - None
        - date
        - general_contractor_name
        - general_contractor_address
        - general_contractor_mail
        - general_contractor_phone
        - general_contractor_license_expiration_date
        - general_contractor_license_number
        - general_contractor_id
        - general_contractor_name
    3:
        - None
        - general_contractor_name

