
  TYPES:
     - supervisor_engineer
     - permit_owner

  3:
      1:
          - None
          - None
          - permit_owner_name
          - supervisor_engineer_address
          - supervisor_engineer_mail 
          - supervisor_engineer_phone
          - supervisor_engineer_license_number
          - supervisor_engineer_id
          - supervisor_engineer_name
          - permit_owner_name
      2:
          - supervisor_engineer_address
          - supervisor_engineer_mail
          - supervisor_engineer_phone
          - supervisor_engineer_license_number
          - supervisor_engineer_id
          - supervisor_engineer_name
      3:
          - None
          - None
          - supervisor_engineer_name