TYPES:
  - supervisor_engineer
  - permit_owner

1:
    1:
        - supervisor_engineer_id
        - supervisor_engineer_name
        - supervisor_engineer_id
        - supervisor_engineer_name
        - supervisor_engineer_phone
        - supervisor_engineer_mail
        - supervisor_engineer_address
        - None
        - None
        - None
        - None
        - permit_owner_name