  TYPES:
     - construction_inspection_officer

  1:
      1:
          - None
          - date
          - construction_inspection_officer_name
          - None
          - construction_inspection_officer_address
          - construction_inspection_officer_mail
          - construction_inspection_officer_phone
          - construction_inspection_officer_license_number
          - construction_inspection_officer_id
          - construction_inspection_officer_name
        
    